image: gcc

build:
  stage: build
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  before_script:
    - apt update && apt -y install make cmake
    - wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
    - gunzip boost_1_72_0.tar.gz
    - tar -xf boost_1_72_0.tar
    - mv boost_1_72_0 /
    - pwd
    - cd /boost_1_72_0/
    - ./bootstrap.sh
    - ./b2 --with-thread --with-system --with-timer --with-filesystem
    - cd /
    - git clone https://github.com/google/googletest
    - cd googletest
    - mkdir build && cd build
    - cmake ..
    - make -j $(nproc)
    - make install
    - ls /
    - cd /
    - git clone https://github.com/protocolbuffers/protobuf.git
    - cd protobuf
    - git checkout 3.11.x
    - git submodule update --init --recursive
    - ./autogen.sh
    - ./configure
    - make -j $(nproc)
    - make install
    - ldconfig # refresh shared library cache.

  script:
    - pwd
    - cd /builds/wangjiaming0909/unp
    - ./scripts/protoc.sh
    - ./scripts/setup_ld.sh
    - make -j $(nproc)
    - make examples -j $(nproc)
    - make test -j $(nproc)
    - ./rt.sh
