build:
    script: "https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz"
    script: "gunzip boost_1_70_0.tar.gz"
    script: "tar -xvf boost_1_70_0.tar"
    script: "mv boost_1_70_0 /"
    script: "sudo apt-get install g++"
    script: "git clont https:github.com/wangjiaming0909/unp"
    script: "cd unp"
    script: "make"

