#!/bin/bash
#dtr57 --suite=main --suite-timeout=1000 --force --force-restart --max-test-fail=100 --retry-failure=0 --skip-test=.*spark.* --valgrind


#grep -E "connect\([^,],[^,].*\).*" ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test > ~/tmp/1
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\(,[^,]*\)\(,[^,]*\)\();\)/\1\2\3, mysql_native_password\4/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\(,[^,]*\)\();\)/\1\2,, mysql_native_password\3/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\();\)/\1,,, mysql_native_password\2/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test

#--enable-pythoninterp=dynamic \
#--with-python3-config-dir=/usr/lib/python3.9/config-3.5m-x86_64-linux-gnu \

./configure --with-features=huge \
--enable-multibyte \
--enable-python3interp=dynamic \
--with-python3-config-dir=/usr/lib/python3.9/config-3.9-x86_64-linux-gnu \
--with-python3-command=python3.9 \
--enable-cscope \
--enable-gui=auto \
--enable-gtk2-check \
--enable-fontset \
--enable-largefile \
--disable-netbeans \
--with-compiledby="jiaming" \
--enable-fail-if-missing \
--prefix=/usr/local \



  --defaults-file=/home/wjm/loads/mysql8_data/8/my.cnf \
  --datadir=/home/wjm/loads/mysql8_data/8 \
  --gdb



#sudo iptables -A INPUT -p tcp --dport 13000 -j DROP

#sudo iptables -L #list
#sudo iptables -F #clear

#sudo tcpdump -vvv -X -i lo tcp port 13002
