#!/bin/bash
#dtr57 --suite=main --suite-timeout=1000 --force --force-restart --max-test-fail=100 --retry-failure=0 --skip-test=.*spark.* --valgrind


#grep -E "connect\([^,],[^,].*\).*" ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test > ~/tmp/1
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\(,[^,]*\)\(,[^,]*\)\();\)/\1\2\3, mysql_native_password\4/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\(,[^,]*\)\();\)/\1\2,, mysql_native_password\3/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test
#sed -i 's/\(connect([^,]*,[^,]*,[^,]*,[^,]*,[^,]*,[^,]*\)\();\)/\1,,, mysql_native_password\2/g' ~/dev/dbscale-chelianwang/dbscale-test8/t/*.test

#--enable-pythoninterp=dynamic \
#--with-python3-config-dir=/usr/lib/python3.9/config-3.5m-x86_64-linux-gnu \
#--with-python3-config-dir=/usr/lib/python3.9/config-3.9-x86_64-linux-gnu \

#--enable-pythoninterp=dynamic \
#--with-python-config-dir=/usr/lib/python2.7/config-x86_64-linux-gnu \
#--with-python-command=python \
#\

#./configure --with-features=huge \
#--enable-multibyte \
#--enable-python3interp=dynamic \
#--with-python3-config-dir=/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu \
#--with-python3-command=python3.7 \
#--enable-cscope \
#--enable-gui=auto \
#--enable-gtk2-check \
#--enable-fontset \
#--enable-largefile \
#--disable-netbeans \
#--with-compiledby="jiaming" \
#--enable-fail-if-missing \
#--prefix=/usr/local \
#
#
#
#  --defaults-file=/home/wjm/loads/mysql8_data/8/my.cnf \
#  --datadir=/home/wjm/loads/mysql8_data/8 \
#  --gdb

#  --defaults-file=/home/wjm/loads/mysql8_data/57/my.cnf \
#  --datadir=/home/wjm/loads/mysql8_data/57 \
#  --gdb



#sudo iptables -A INPUT -p tcp --dport 9090 -j DROP

#sudo iptables -L #list
sudo iptables -F #clear

#sudo tcpdump -vvv -X -i lo tcp port 13002
#sqlplus zjtest/zjtest@172.16.50.106:1521/great

#-------------------------
#kd
#kmysqld
#rm -rf /tmp/recover_dir/*
#
#
#ulimit -n 9999
#cd ~/dev/dbscale-chelianwang/dbscale-test
#dtr57 t/my.test 2> /dev/null &
#
#sleep 20
#
#cd ~/Documents/dbscale_backup
#./prepare 3307 2> /dev/null &
#
#sleep 30
#
#cd ~/dev/dbscale-chelianwang/extra/dbscale-backup-tool/
#./backup.py
#
#sleep 2
#kd
#kmysqld

#./recovery
#---------------------------------------

#rotate screen in the tty
#0, 1, 2, 3
#echo 0 > /sys/class/graphics/fbcon/rotate_all

mysql -uroot -h127.0.0.1 -P13000 -e "grant all on *.* to root@'%'; create user jiaming@'%' identified by 'asd'; grant all on *.* to jiaming@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13001 -e "grant all on *.* to root@'%'; create user jiaming1@'%' identified by 'asd1'; grant all on *.* to jiaming1@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13002 -e "grant all on *.* to root@'%'; create user jiaming2@'%' identified by 'asd2'; grant all on *.* to jiaming2@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13003 -e "grant all on *.* to root@'%'; create user jiaming3@'%' identified by 'asd3'; grant all on *.* to jiaming3@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13004 -e "grant all on *.* to root@'%'; create user jiaming4@'%' identified by 'asd4'; grant all on *.* to jiaming4@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13005 -e "grant all on *.* to root@'%'; create user jiaming5@'%' identified by 'asd5'; grant all on *.* to jiaming5@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13006 -e "grant all on *.* to root@'%'; create user jiaming6@'%' identified by 'asd6'; grant all on *.* to jiaming6@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13007 -e "grant all on *.* to root@'%'; create user jiaming7@'%' identified by 'asd7'; grant all on *.* to jiaming7@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13008 -e "grant all on *.* to root@'%'; create user jiaming8@'%' identified by 'asd8'; grant all on *.* to jiaming8@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13009 -e "grant all on *.* to root@'%'; create user jiaming9@'%' identified by 'asd9'; grant all on *.* to jiaming9@'%';reset master;"
mysql -uroot -h127.0.0.1 -P13010 -e "grant all on *.* to root@'%'; create user jiaming10@'%' identified by 'asd10'; grant all on *.* to jiaming10@'%';reset master;"

#python -m pip install --upgrade pip
