#!/bin/bash

#sudo iptables -A INPUT -p tcp --dport 3308 -j DRO
#sudo iptables -A INPUT -p tcp --dport 3309 -j DROP
sudo iptables -A INPUT -p tcp --dport 13001 -j DROP
sudo iptables -A INPUT -p tcp --dport 13000 -j DROP
sudo iptables -A INPUT -p tcp --dport 13004 -j DROP

